### ISSUE TITLE
Improvement feature request

### ISSUE THREAD

**Issue by faslurrajah** [ghpranav/link_preview_generator#1]
added showtitle, showBody bool
disable option url launcher when press the widget 
adjust the box fit of graphics.

**Comment by ghpranav** [comment]
Thanks for the suggestions! I'll definitely be working on adding these features as soon as possible for the upcoming release.

**Comment by ghpranav** [comment]
All the requested features have been completely implemented & will be included in the next release version 1.1.0. Thank you for waiting. I'm closing this issue, feel free to open a new one if you need any more features.
